<section class="Banner--internal">
	<div class="Banner__item" style="background-image: url(assets/img/banner-consignacao.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1 class="wow fadeInUp" data-wow-delay=".3s">Consignação</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</div>
</section> <!-- Banner -->

<div class="Generic">
<div class="container">
  <h3 class="wow fadeIn">DEIXE SEU VEÍCULO COM A GENTE!</h3>
  
  <p class="wow fadeIn" data-wow-delay=".15s">
  A venda consignada é uma forma de negociar seu veículo com segurança e tranquilidade. Oferecemos nossa estrutura e uma carteira de clientes com alto poder de compra, além da divulgação em nosso site e redes sociais. É muito fácil. Você traz seu veículo, combinamos o valor e assinamos o contrato. Assim que a venda se concretizar, você será notificado para a formalização do negócio. Entre em contato conosco.
  </p>

  <div class="Form wow fadeIn" data-wow-delay=".3s">
   
    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="nome" placeholder="NOME">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half">
        <input type="text" name="documento" placeholder="SEU CPF OU CNPJ">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>

    <div class="Form__control" data-validate="true">
      <input type="text" name="endereco" placeholder="SEU ENDEREÇO COMPLETO">
      <span class="Form__required">*</span>
    </div> <!-- Form__control -->

    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="cidade" placeholder="CIDADE">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="estado" placeholder="ESTADO">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>
    
    <div>
      <div class="Form__control--half">
        <input type="tel" name="telefone" placeholder="TELEFONE">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->

      <div class="Form__control--half" data-validate="true">
        <input type="email" name="email" placeholder="EMAIL">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>
	
	<h3>DADOS DO VEÍCULO</h3>
	
    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="marca" placeholder="MARCA">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="modelo" placeholder="MODELO">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>
    
    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="anoModelo" placeholder="ANO/MODELO">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="odometro" placeholder="ODÔMETRO (KM)">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>
    
    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="motor" placeholder="MOTOR">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="combustivel" placeholder="COMBUSTÍVEL">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>

	  <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="portas" placeholder="PORTAS">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="placa" placeholder="PLACA">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
    </div>
    
   <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="renavan" placeholder="RENAVAN">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="chassi" placeholder="CHASSI">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
   </div>
    
    <div>
      <div class="Form__control--half" data-validate="true">
        <input type="text" name="valor" placeholder="VALOR ESTIMADO">
        <span class="Form__required">*</span>
      </div> <!-- Form__control -->
      
      <div class="Form__control--half u-taLeft">
        <input type="checkbox" name="disponibilidade" id="checkbox_newsletter">
        <label for="checkbox_newsletter">POSSO DEIXAR O VEÍCULO NA LOJA</label>
      </div>
    </div>

    <div class="Form__control" data-validate="true">
      <textarea rows="3" cols="30" placeholder="OBS (EX: TENHO INTERESSE NO CARRO BMW...)"></textarea>
      <span class="Form__required">*</span>
    </div>

    <div class="Form__control">
      <a href="#/" class="u-button js-submitForm"><span>enviar</span></a>
    </div>
  </div> <!-- Form -->
</div> <!-- container -->
</div> <!-- Proposta -->