<section class="Banner js-sliderBanner">
	<div class="Banner__item" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1>Lorem <span>Ipsum</span> é simplesmente uma simulação de texto</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</div> <!-- Banner__item -->

	<div class="Banner__item" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1>Lorem <span>Ipsum</span> é simplesmente uma simulação de texto 2</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</div> <!-- Banner__item -->

	<div class="Banner__item" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1>Lorem <span>Ipsum</span> é simplesmente uma simulação de texto 3</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</div> <!-- Banner__item -->
</section> <!-- Banner -->

<section class="Busca">
	<div class="container">
		<p>busque por tipo, marca, modelo ou outros tipos de veículos</p>

		<form class="Form" action="estoque" method="get">
			<div class="Form__control--search">
				<input type="hidden" name="pg" value="0">
				<input type="text" name="input_busca" value="<?=$valor2?>">
			</div>
		</form>
	</div>
</section> <!-- Busca -->

<section class="Grid" id="estoque">
	
	<?php
		
		//Seleciona veciculos destacados
		$veiculoHome = DAOFactory::getVeiculoDAO()->queryCondList(' status="2" ORDER BY idVeiculo DESC LIMIT 12 ');
		for($i=0;$i<count($veiculoHome);$i++){ 
			
			$rowVeiculoHome = $veiculoHome[$i]; 	
			
			$marca = DAOFactory::getMarcaDAO()->load($rowVeiculoHome->idMarca);
			$capa = DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowVeiculoHome->idAlbum.'" ORDER BY ordem ASC LIMIT 1 '); 
		
	?>	
	
		<div class="Grid__item" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowVeiculoHome->idAlbum?>/<?=$capa[0]->file?>);">
			<div class="Grid__title">
				<h4><?=$marca->nome?> <?=$rowVeiculoHome->modelo?><small><?=$rowVeiculoHome->anoFabricacao?> - <?=$rowVeiculoHome->anoModelo?></small></h4>
			</div> <!-- Grid__title -->
	
			<div class="Grid__buttons">
				<a href="/estoque/<?=$rowVeiculoHome->alias?>/<?=$rowVeiculoHome->alias?>">VER DETALHES</a>
				<a href="/estoque/<?=$rowVeiculoHome->alias?>/<?=$rowVeiculoHome->alias?>#proposta">FAZER PROPOSTA</a>
			</div> <!-- Grid__buttons -->
		</div> <!-- Grid__item -->

		
	<?php } ?>
		
</section> <!-- Grid -->

<section class="Ver">
	<div class="container">
		<a href="/estoque" class="u-button">
			<span>ver estoque completo</span>
		</a>
	</div>
</section> <!-- Ver -->

<section id="servicos" class="Info">
	<div class="Info__item wow fadeIn" style="visibility: visible; animation-name: fadeIn;">
		<div class="Info__content">
			<h3>NÃO ENCONTROU?</h3>
			<small>Envia seus dados para nosso<br>setor financeiro</small>
			<a href="#/" class="u-button wow fadeInUp" data-toggle="modal" data-target="#modalFinanciamento" style="visibility: visible; animation-name: fadeInUp;"><span>simular</span></a>
		</div> <!-- Info__content -->
	</div> <!-- Info__item -->

	<div class="Info__item wow fadeIn" data-wow-delay=".2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeIn;">
		<div class="Info__content">
			<h3>VENDA SEU VEÍCULO?</h3>
			<small>Envia seus dados para nosso<br>setor análise</small>
			<a href="#/" class="u-button wow fadeInUp" data-wow-delay=".3s" data-toggle="modal" data-target="#modalAvalie" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;"><span>avaliar</span></a>
		</div> <!-- Info__content -->
	</div> <!-- Info__item -->

	<div class="Info__item wow fadeIn" data-wow-delay=".4s" style="visibility: visible; animation-delay: 0.4s; animation-name: fadeIn;">
		<div class="Info__content">
			<h3>DESEJA FINANCIAR</h3>
			<small>Envia seus dados para nosso<br>setor atendimento</small>
			<a href="#/" class="u-button wow fadeInUp" data-wow-delay=".5s" data-toggle="modal" data-target="#modalContato" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;"><span>solicitar</span></a>
		</div> <!-- Info__content -->					
	</div> <!-- Info__item -->
	</section>

<section class="Geral">
	<div class="container">
			<h3 class="wow fadeIn" style="visibility: visible; animation-name: fadeIn;">ACOMPANHE NOSSO <span>INSTAGRAM</span></h3>
	</div>
</section>

<section id="instafeed" class="Instafeed">
</section>