<section class="Banner--internal js-sliderBanner">
	<a class="Banner__item" data-fancybox="banner-sobre" href="assets/img/banner.jpg" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1 class="wow fadeInUp" data-wow-delay=".3s">Sobre</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</a>
	<a class="Banner__item" data-fancybox="banner-sobre" href="assets/img/banner.jpg" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1 class="wow fadeInUp" data-wow-delay=".3s">Sobre 2</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
</a>
</section> <!-- Banner -->

<div class="Generic Sobre">
<div class="container">
  <h3>DEIXE SEU VEÍCULO COM A GENTE!</h3>
  
  <p class="text-left">A Rosalvo Automóveis nasceu, em 1988, quando Rosalvo, fundador da empresa, resolveu se desligar da Mesbla Veículos – conceituada revenda Ford -  após mais de dez anos de serviços prestados e abrir seu próprio negócio. Com 40 anos de experiência no mercado automotivo, Rosalvo se tornou uma referência em Minas Gerais pelo alto padrão de qualidade de seu estoque, exigência na prestação de serviços e transparência nos relacionamentos de sua empresa.</p>
	
<p>Com objetivo de oferecer aos clientes um produto diferenciado, a Rosalvo Automóveis se destaca pelo rigoroso critério técnico de avaliação dos veículos, garantindo sempre a alta qualidade e procedência. A empresa também oferece o serviço de consignação, pós-venda e consultoria para negociações particulares. Trabalhamos com os melhores bancos e as menores taxas para financiamento. Aceitamos consórcio.</p>
	
	<h3>Missão</h3>
	<p>Atender à expectativa dos nossos clientes, prezar sempre pela qualidade diferenciada dos nossos veículos e, assim, ser a melhor e mais segura opção do mercado de seminovos.</p>
	
	<h3>Visão</h3>
	<p>Ser uma empresa modelo, reconhecida como a melhor do segmento por clientes, colaboradores, comunidade e parceiros, devido à nossa seriedade e qualidade dos veículos, serviços e relacionamento.</p>
	
	<h3>Valores</h3>
	<ul class="u-ul">
		<li>Ética, Integridade e Confiança</li>
		<li>Paixão pelo que fazemos</li>
		<li>Proximidade ao cliente</li>
		<li>Ambiente familiar</li>
		<li>Foco em resultado</li>
		<li>Melhoria contínua</li>
	</ul>
  </p>
  
</div>
</div>