<section class="Banner--internal">
	<div class="Banner__item" style="background-image: url(assets/img/banner.jpg);">
		<div class="container">
			<div class="Banner__content">
				<h1 class="wow fadeInUp" data-wow-delay=".3s">Sobre</h1>
			</div> <!-- Banner-content -->
		</div> <!-- container -->
	</div>
</section> <!-- Banner -->

<div class="Generic">
<div class="container">
  <h3>DEIXE SEU VEÍCULO COM A GENTE!</h3>
  
  <p>
	A Rosalvo Automóveis foi fundada em 1988 com o objetivo de revolucionar o conceito de comercialização de veículos semi-novos.</p>
	
	<h3>Missão</h3>
	<p>Prestar um serviço de qualidade buscando a satisfação e fidelidade de seus clientes.</p>
	
	<h3>Visão</h3>
	<p>Ser líder no mercado de comercialização de veículos.</p>
	
	<h3>Valores</h3>
	<ul class="u-ul">
		<li>Ética</li>
		<li>Excelencia</li>
		<li>Flexibilidade</li>
		<li>Competência</li>
		<li>Credibilidade</li>
	</ul>
  </p>
  
</div>
</div>